#!/usr/bin/env node

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import {
  calibrateStructureModel,
  evaluateStructureModel,
  liveParametersMatchCalibration,
  splitStructureStorms,
} from '../src/structure-validation.ts';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const DATA_PATH = resolve(
  ROOT,
  'calibration/data/ibtracs-ni-jtwc-2019-2024.json',
);
const RESULTS_PATH = resolve(ROOT, 'calibration/results.json');
const REPORT_PATH = resolve(ROOT, 'docs/structure-calibration.md');
const CHECK = process.argv.includes('--check');

function metricCell(metric) {
  if (!metric || metric.mae === null) return '—';
  return `${metric.mae.toFixed(1)} / ${metric.bias.toFixed(1)} / ${metric.rmse.toFixed(1)} (${metric.count})`;
}

function percent(value) {
  return `${(value * 100).toFixed(1)}%`;
}

function changedParameters(baseline, proposed) {
  return Object.keys(baseline)
    .filter((key) => baseline[key] !== proposed[key])
    .map((key) => ({
      key,
      baseline: baseline[key],
      proposed: proposed[key],
    }));
}

function metricsTable(baseline, proposed, deployed) {
  const rows = [
    ['Pressure', 'hPa', 'pressure'],
    ['R34 quadrants', 'km', 'r34'],
    ['R50 quadrants', 'km', 'r50'],
    ['R64 quadrants', 'km', 'r64'],
    ['RMW exploratory', 'km', 'rmw'],
  ];
  return [
    '| Metric | Unit | Baseline MAE / bias / RMSE (n) | Proposed MAE / bias / RMSE (n) | Deployed MAE / bias / RMSE (n) |',
    '| --- | --- | ---: | ---: | ---: |',
    ...rows.map(
      ([label, unit, key]) =>
        `| ${label} | ${unit} | ${metricCell(baseline.metrics[key])} | ${metricCell(proposed.metrics[key])} | ${metricCell(deployed.metrics[key])} |`,
    ),
  ].join('\n');
}

function sliceTable(title, deployedSlices) {
  const rows = [];
  for (const key of Object.keys(deployedSlices).sort()) {
    const deployed = deployedSlices[key];
    if (!deployed) continue;
    rows.push(
      `| ${key} | ${metricCell(deployed.pressure)} | ${metricCell(deployed.r34)} | ${metricCell(deployed.r50)} | ${metricCell(deployed.r64)} | ${metricCell(deployed.rmw)} |`,
    );
  }
  if (rows.length === 0) return '';
  return [
    `### ${title}`,
    '',
    '| Slice | Pressure | R34 | R50 | R64 | RMW exploratory |',
    '| --- | ---: | ---: | ---: | ---: | ---: |',
    ...rows,
  ].join('\n');
}

function makeMarkdown(dataset, split, result, fullDeployed) {
  const changed = changedParameters(
    result.baselineParameters,
    result.proposedParameters,
  );
  const verdict = result.accepted
    ? 'ACCEPTED — the proposed calibration cleared every held-out gate and is eligible for the live model.'
    : 'REJECTED — the live model remains on the pre-calibration parameters.';
  const changedRows =
    changed.length === 0
      ? '| None | — | — |'
      : changed
          .map(
            ({ key, baseline, proposed }) =>
              `| \`${key}\` | ${baseline} | ${proposed} |`,
          )
          .join('\n');

  return `# North Indian Ocean physical-structure calibration

> Deterministic report generated by \`npm run calibrate:structure\`. Do not edit
> metric values by hand.

## Verdict

**${verdict}**

${result.reason}. Held-out objective change:
**${percent(result.validationImprovementFraction)}**. The search evaluated
${result.evaluatedCandidates} unique parameter sets using calibration storms
only.

## Data contract

- Source: [${dataset.source.name}](${dataset.source.url}), North Indian basin,
  USA/JTWC columns, snapshot ${dataset.source.snapshotDate}.
- Pinned source SHA-256: \`${dataset.source.sha256}\`.
- Sample: ${dataset.counts.storms} storms and ${dataset.counts.fixes} six-hour
  main-track tropical fixes from ${dataset.selection.seasons[0]}–${dataset.selection.seasons[1]}.
- Calibration split: ${split.calibration.length} complete storms.
- Untouched validation split: ${split.validation.length} complete storms.
- R34 scoring starts in 2019. R50/R64 scoring starts in 2022.
- RMW is exploratory only and is excluded from parameter selection.
- Central pressure is treated as moderate-confidence validation.
- USA/JTWC position, one-minute wind, pressure, RMW and quadrant radii are kept
  together; the extractor never mixes structure values from different agencies.

Validation storm IDs:

\`${split.validation.join('`, `')}\`

## Protocol

Each observation conditions the live \`src/structure.ts\` model on observed
one-minute intensity, latitude, land proximity and a centred finite-difference
track-motion vector. The model evolves its own RMW through each storm in time
order. IBTrACS has no environmental-shear field, so validation uses a declared
neutral shear of 8 m/s. This isolates the parametric structure contract; it is
not a historical atmosphere replay.

Parameter search minimizes the mean normalized MAE of pressure, R34, R50 and
R64 on calibration storms. The held-out candidate is accepted only if:

1. objective improves by at least 2%;
2. pressure MAE stays within 2% of baseline;
3. combined wind-radius MAE improves; and
4. no individual wind threshold regresses by more than 5%.

## Held-out results

Objective: baseline **${result.baselineValidation.objective.toFixed(3)}**,
proposed **${result.proposedValidation.objective.toFixed(3)}**, deployed
**${result.deployedValidation.objective.toFixed(3)}**.

Metric cells are **MAE / bias / RMSE (sample count)**.

${metricsTable(
  result.baselineValidation,
  result.proposedValidation,
  result.deployedValidation,
)}

## Proposed parameter changes

| Parameter | Baseline | Proposed |
| --- | ---: | ---: |
${changedRows}

## Held-out slices

${sliceTable(
  'By intensity',
  result.deployedValidation.slices.intensity,
)}

${sliceTable(
  'By subbasin',
  result.deployedValidation.slices.subbasin,
)}

${sliceTable(
  'By lifecycle',
  result.deployedValidation.slices.lifecycle,
)}

${sliceTable(
  'By quadrant',
  result.deployedValidation.slices.quadrant,
)}

## Full-sample deployed reference

Across all ${fullDeployed.storms} storms, the deployed model has objective
**${fullDeployed.objective.toFixed(3)}** and combined R34/R50/R64 MAE
**${fullDeployed.combinedRadiusMaeKm?.toFixed(1) ?? '—'} km**.

## Limitations

- JTWC reports routine R34 quality control only from 2019, and stronger
  R50/R64 quality control from 2022.
- JTWC RMW remains non-QC; it is shown for diagnosis but cannot tune the model.
- Best-track pressure is not aircraft ground truth in this basin.
- Neutral shear means this report cannot calibrate the model's shear-broadening
  terms.
- Positive reported radii are scored; blank/zero operational cells are treated
  as unavailable, not as observed zero-size quadrants.
- The validation split is a model-development holdout, not an independent
  operational forecast trial.

## Reproduce

\`\`\`bash
python3 bake/extract_structure_validation.py
npm run calibrate:structure
npm run calibrate:check
\`\`\`

The first command requires the pinned raw IBTrACS download under
\`data/raw/ibtracs.NI.csv\`. The committed normalized subset lets CI run the
calibration check without downloading external data.
`;
}

async function compare(path, expected) {
  try {
    const actual = await readFile(path, 'utf8');
    return actual === expected;
  } catch {
    return false;
  }
}

const dataset = JSON.parse(await readFile(DATA_PATH, 'utf8'));
const split = splitStructureStorms(dataset.observations);
const result = calibrateStructureModel(dataset.observations);
const fullDeployed = evaluateStructureModel(
  dataset.observations,
  result.deployedParameters,
  'all',
);
const liveParametersMatch = liveParametersMatchCalibration(result);

const output = {
  schemaVersion: 1,
  dataset: {
    source: dataset.source,
    selection: dataset.selection,
    counts: dataset.counts,
    split,
  },
  protocol: {
    neutralShearMs: 8,
    objective:
      'mean normalized MAE: pressure/15 hPa, R34/100 km, R50/75 km, R64/50 km',
    rmwInObjective: false,
    minimumHeldOutImprovementFraction: 0.02,
    maximumPressureRegressionFraction: 0.02,
    maximumPerThresholdRegressionFraction: 0.05,
    requireCombinedRadiiImprovement: true,
  },
  calibration: result,
  fullDeployed,
  liveParametersMatch,
};
const resultsText = `${JSON.stringify(output, null, 2)}\n`;
const reportText = makeMarkdown(dataset, split, result, fullDeployed);

if (CHECK) {
  const resultsMatch = await compare(RESULTS_PATH, resultsText);
  const reportMatches = await compare(REPORT_PATH, reportText);
  if (!resultsMatch || !reportMatches || !liveParametersMatch) {
    console.error(
      `[structure-calibration] FAIL results=${resultsMatch} report=${reportMatches} liveParameters=${liveParametersMatch}`,
    );
    process.exitCode = 1;
  } else {
    console.log(
      `[structure-calibration] PASS ${dataset.counts.storms} storms; held-out objective ${result.deployedValidation.objective.toFixed(3)}`,
    );
  }
} else {
  await mkdir(dirname(REPORT_PATH), { recursive: true });
  await writeFile(RESULTS_PATH, resultsText);
  await writeFile(REPORT_PATH, reportText);
  console.log(
    `[structure-calibration] wrote calibration/results.json and docs/structure-calibration.md`,
  );
  console.log(
    `[structure-calibration] proposed=${result.accepted ? 'ACCEPTED' : 'REJECTED'} held-out change=${percent(result.validationImprovementFraction)} liveParameters=${liveParametersMatch}`,
  );
}
